# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSvI1NNOrk6yqXiZ5yw2lyrlck2gYV1G
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

st.title("VIX vs S&P 500 Analysis Dashboard")

tab1, tab2 = st.tabs(["Real Data Analysis", "Synthetic Prediction"])

with tab1:
    st.subheader("Real Data (Yahoo Finance API)")
    start_date = "2020-01-01"
    end_date = "2025-01-01"
    sp500 = yf.download("^GSPC", start=start_date, end=end_date, auto_adjust=True)
    vix = yf.download("^VIX", start=start_date, end=end_date, auto_adjust=True)
    merged = pd.merge(
        sp500.reset_index()[["Date", "Close"]].rename(columns={"Close": "SP500_Close"}),
        vix.reset_index()[["Date", "Close"]].rename(columns={"Close": "VIX_Close"}),
        on="Date",
        how="inner",
    )
    merged["SP500_Returns"] = merged["SP500_Close"].pct_change() * 100
    merged["VIX_Change"] = merged["VIX_Close"].pct_change() * 100
    merged.dropna(inplace=True)

    corr = merged["SP500_Returns"].corr(merged["VIX_Change"])
    st.metric("Correlation (VIX Change vs S&P 500 Returns)", f"{corr:.4f}")

    fig, ax = plt.subplots()
    sns.scatterplot(x="VIX_Change", y="SP500_Returns", data=merged, ax=ax, alpha=0.6)
    st.pyplot(fig)

    merged["Rolling_Corr"] = merged["VIX_Close"].rolling(30).corr(merged["SP500_Returns"])
    fig2, ax2 = plt.subplots()
    ax2.plot(merged["Date"], merged["Rolling_Corr"], color="purple")
    ax2.set_title("30-Day Rolling Correlation")
    st.pyplot(fig2)

with tab2:
    st.subheader("Synthetic Data Prediction (Simulated Model)")
    np.random.seed(42)
    dates = pd.date_range(start="2020-01-01", end="2024-12-31", freq="B")
    vix_vals = 20 + np.random.normal(0, 3, len(dates)).cumsum() / 20
    sp500_vals = 3000 + np.random.normal(0, 15, len(dates)).cumsum()
    df = pd.DataFrame({"Date": dates, "VIX": vix_vals, "SP500": sp500_vals})
    df["VIX_Change"] = df["VIX"].pct_change() * 100
    df["SP500_Returns"] = df["SP500"].pct_change() * 100
    df.dropna(inplace=True)

    X = df[["VIX_Change"]]
    y = df["SP500_Returns"]
    model = LinearRegression().fit(X, y)
    y_pred = model.predict(X)
    rmse = np.sqrt(mean_squared_error(y, y_pred))
    r2 = r2_score(y, y_pred)

    st.metric("RMSE", f"{rmse:.4f}")
    st.metric("R² Score", f"{r2:.4f}")

    fig3, ax3 = plt.subplots()
    ax3.scatter(y, y_pred, alpha=0.5)
    ax3.set_xlabel("Actual Returns")
    ax3.set_ylabel("Predicted Returns")
    st.pyplot(fig3)

    new_vix = st.slider("Simulate VIX Change (%)", -10.0, 10.0, 0.0, 0.5)
    pred = model.predict([[new_vix]])[0]
    st.success(f"Predicted S&P 500 Return for VIX Change {new_vix:.2f}% → {pred:.2f}%")