# -*- coding: utf-8 -*-
"""Datapython1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNIG6CHmnLXYuFJWYbN8KrlnuGkmVEvY
"""

# -------------------------------------------------
# VIX vs S&P 500 Returns Correlation Analysis with Rolling Correlation
# -------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

# 1. Download 5 years of data
start_date = "2020-01-01"
end_date = "2025-01-01"

sp500 = yf.download("^GSPC", start=start_date, end=end_date, auto_adjust=True)
vix = yf.download("^VIX", start=start_date, end=end_date, auto_adjust=True)

# 2. Keep only Date and Close columns
sp500 = sp500.reset_index()[["Date", "Close"]].rename(columns={"Close": "SP500_Close"})
vix = vix.reset_index()[["Date", "Close"]].rename(columns={"Close": "VIX_Close"})

# 3. Merge datasets
merged_data = pd.merge(sp500, vix, on="Date", how="inner")

# 4. Compute S&P 500 daily returns (%)
merged_data["SP500_Returns"] = merged_data["SP500_Close"].pct_change() * 100

# 5. Drop NaN values
cleaned_data = merged_data[["Date", "VIX_Close", "SP500_Returns"]].dropna().copy()

# 6. Ensure both columns are 1D numeric Series
vix_series = pd.to_numeric(cleaned_data["VIX_Close"].squeeze(), errors="coerce")
returns_series = pd.to_numeric(cleaned_data["SP500_Returns"].squeeze(), errors="coerce")

# 7. Drop any remaining NaN values
mask = ~(vix_series.isna() | returns_series.isna())
vix_series = vix_series[mask]
returns_series = returns_series[mask]
cleaned_data = cleaned_data.loc[mask]

# 8. Compute correlation
correlation = np.corrcoef(vix_series, returns_series)[0, 1]
print(f"\nCorrelation between VIX and S&P 500 Returns: {correlation:.4f}")

# 9. Scatter plot with trendline
plt.figure(figsize=(10, 6))
plt.scatter(vix_series, returns_series, alpha=0.6, label="Daily Data")
m, b = np.polyfit(vix_series, returns_series, 1)
plt.plot(vix_series, m*vix_series + b, color="red", label="Trendline")
plt.title("VIX vs S&P 500 Daily Returns (2020–2025)")
plt.xlabel("VIX Close")
plt.ylabel("S&P 500 Daily Returns (%)")
plt.legend()
plt.grid(True)
plt.show()

# 10. Rolling 30-day correlation
window_size = 30
cleaned_data["Rolling_Corr"] = (
    cleaned_data["VIX_Close"]
    .rolling(window_size)
    .corr(cleaned_data["SP500_Returns"])
)

# 11. Plot rolling correlation
plt.figure(figsize=(12, 6))
plt.plot(cleaned_data["Date"], cleaned_data["Rolling_Corr"], color="purple", linewidth=2)
plt.axhline(0, color="gray", linestyle="--", linewidth=1)
plt.title(f"30-Day Rolling Correlation between VIX and S&P 500 Returns ({window_size}-day window)")
plt.xlabel("Date")
plt.ylabel("Rolling Correlation")
plt.grid(True)
plt.show()

# 12. Show sample data
print("\nSample Data with Rolling Correlation:")
print(cleaned_data.head())