# -*- coding: utf-8 -*-
"""DataPython2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13R7mFAcECKKxv-iU05saldFzbnV45R9j
"""

# ===============================================
# 📊 VIX vs S&P 500 Data Analysis + Prediction
# ===============================================

# 1. Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from datetime import datetime, timedelta

# 2. Generate synthetic VIX and S&P 500 data (for demo)
np.random.seed(42)
dates = pd.date_range(start="2020-01-01", end="2024-12-31", freq="B")

# Simulate VIX (Volatility Index) and S&P 500 closing prices
vix_values = 20 + np.random.normal(0, 3, len(dates)).cumsum() / 20
sp500_values = 3000 + np.random.normal(0, 15, len(dates)).cumsum()

# Build DataFrames
vix_data = pd.DataFrame({"Date": dates, "Close": vix_values})
sp500_data = pd.DataFrame({"Date": dates, "Close": sp500_values})

# 3. Preprocess data
vix_data["Date"] = pd.to_datetime(vix_data["Date"])
sp500_data["Date"] = pd.to_datetime(sp500_data["Date"])

# 4. Merge on Date
merged_data = pd.merge(vix_data, sp500_data, on="Date", suffixes=("_VIX", "_SP500"))

# 5. Feature engineering
merged_data["SP500_Returns"] = merged_data["Close_SP500"].pct_change() * 100
merged_data["VIX_Change"] = merged_data["Close_VIX"].pct_change() * 100

# Drop missing rows
cleaned_data = merged_data.dropna(subset=["SP500_Returns", "VIX_Change"])

# 6. Correlation analysis
correlation = cleaned_data["SP500_Returns"].corr(cleaned_data["VIX_Change"])
print(f"Correlation between VIX Change and S&P 500 Returns: {correlation:.4f}")

# 7. Data visualization
plt.figure(figsize=(10, 5))
sns.scatterplot(x="VIX_Change", y="SP500_Returns", data=cleaned_data, alpha=0.5)
plt.title("VIX % Change vs S&P 500 Returns")
plt.xlabel("VIX % Change")
plt.ylabel("S&P 500 % Returns")
plt.grid(True)
plt.show()

# 8. Train-test split for prediction
X = cleaned_data[["VIX_Change"]]
y = cleaned_data["SP500_Returns"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 9. Build and train model
model = LinearRegression()
model.fit(X_train, y_train)

# 10. Predict and evaluate
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"\nModel Evaluation:")
print(f"RMSE: {rmse:.4f}")
print(f"R² Score: {r2:.4f}")

# 11. Plot actual vs predicted
plt.figure(figsize=(10, 5))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.xlabel("Actual Returns")
plt.ylabel("Predicted Returns")
plt.title("Actual vs Predicted S&P 500 Returns (Based on VIX Changes)")
plt.grid(True)
plt.show()

# 12. Optional: Save to CSV
merged_data.to_csv("synthetic_vix_sp500_data.csv", index=False)
print("\n✅ Synthetic data and model training completed successfully!")
!pip install shap --quiet
import shap

# Create SHAP explainer
explainer = shap.Explainer(model, X_test)
shap_values = explainer(X_test)

# Display summary plot
shap.summary_plot(shap_values, X_test)